// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Hashtag defines model for Hashtag.
type Hashtag struct {
	// Indices Start and end indices in the tweet text
	Indices []int `json:"indices"`

	// Text Hashtag text (without
	Text string `json:"text"`
}

// Media defines model for Media.
type Media struct {
	// DisplayUrl Display URL for media
	DisplayUrl string `json:"display_url"`

	// ExpandedUrl Expanded URL for media
	ExpandedUrl string `json:"expanded_url"`

	// IdStr Media unique identifier
	IdStr string `json:"id_str"`

	// Indices Start and end indices in the tweet text
	Indices []int `json:"indices"`

	// MediaKey Media key identifier
	MediaKey string `json:"media_key"`

	// MediaUrlHttps HTTPS media URL
	MediaUrlHttps string `json:"media_url_https"`

	// Type Media type (photo, video, etc.)
	Type string `json:"type"`

	// Url Media URL
	Url string `json:"url"`
}

// MentionSummary defines model for MentionSummary.
type MentionSummary struct {
	// Cid Content identifier (CID)
	Cid string `json:"cid"`

	// ContentPreview Mention content preview/summary
	ContentPreview string `json:"content_preview"`

	// CreatedAt Mention creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Id Mention unique identifier
	Id string `json:"id"`

	// MentionCreateAt Mention tweet creation timestamp
	MentionCreateAt time.Time `json:"mention_create_at"`

	// NumTweets Number of tweets in the thread
	NumTweets    int           `json:"num_tweets"`
	ThreadAuthor *ThreadAuthor `json:"thread_author,omitempty"`

	// ThreadId Thread unique identifier
	ThreadId string `json:"thread_id"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	// Limit Maximum number of items returned
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// Total Total number of items
	Total int `json:"total"`
}

// Symbol defines model for Symbol.
type Symbol struct {
	// Indices Start and end indices in the tweet text
	Indices []int `json:"indices"`

	// Text Symbol text (without $)
	Text string `json:"text"`
}

// ThreadAuthor defines model for ThreadAuthor.
type ThreadAuthor struct {
	// Id Author's unique identifier (Twitter user ID)
	Id string `json:"id"`

	// Name Author's display name
	Name string `json:"name"`

	// ProfileImageUrl Author's profile image URL
	ProfileImageUrl string `json:"profile_image_url"`

	// ScreenName Author's screen name (without @)
	ScreenName string `json:"screen_name"`
}

// ThreadDetail defines model for ThreadDetail.
type ThreadDetail struct {
	// Cid Content identifier (CID)
	Cid string `json:"cid"`

	// ContentPreview Thread content preview/summary
	ContentPreview string `json:"content_preview"`

	// CreatedAt Thread creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Id Thread unique identifier
	Id string `json:"id"`

	// NumTweets Number of tweets in the thread
	NumTweets int `json:"num_tweets"`

	// Tweets Tweets associated with this Thread
	Tweets *[]Tweet `json:"tweets"`
}

// Timestamp defines model for Timestamp.
type Timestamp struct {
	// Indices Start and end indices in the text
	Indices []int `json:"indices"`

	// Seconds Seconds value of timestamp
	Seconds int `json:"seconds"`

	// Text Timestamp text
	Text string `json:"text"`
}

// Tweet defines model for Tweet.
type Tweet struct {
	Author *TweetUser `json:"author,omitempty"`

	// ConversationId Conversation thread identifier
	ConversationId string `json:"conversation_id"`

	// CreatedAt Tweet creation timestamp
	CreatedAt time.Time      `json:"created_at"`
	Entities  *TweetEntities `json:"entities,omitempty"`

	// HasBirdwatchNotes Whether this tweet has Birdwatch notes
	HasBirdwatchNotes bool `json:"has_birdwatch_notes"`

	// Id Tweet unique identifier
	Id string `json:"id"`

	// InReplyToStatusId ID of the tweet this is replying to
	InReplyToStatusId *string `json:"in_reply_to_status_id"`

	// InReplyToUserId ID of the user this is replying to
	InReplyToUserId *string `json:"in_reply_to_user_id"`

	// IsQuoteStatus Whether this is a quote tweet
	IsQuoteStatus bool `json:"is_quote_status"`

	// IsReply Whether this is a reply
	IsReply bool `json:"is_reply"`

	// IsRetweet Whether this is a retweet
	IsRetweet bool `json:"is_retweet"`

	// IsTranslatable Whether tweet can be translated
	IsTranslatable bool `json:"is_translatable"`

	// Lang Tweet language code
	Lang string `json:"lang"`

	// PossiblySensitive Whether content might be sensitive
	PossiblySensitive bool   `json:"possibly_sensitive"`
	QuotedTweet       *Tweet `json:"quoted_tweet,omitempty"`

	// RestId Tweet REST API identifier
	RestId string `json:"rest_id"`

	// Source Source application
	Source *string    `json:"source"`
	Stats  TweetStats `json:"stats"`

	// Text Tweet text content
	Text string `json:"text"`

	// Views Number of views
	Views *int `json:"views"`
}

// TweetEntities defines model for TweetEntities.
type TweetEntities struct {
	// Hashtags Hashtags in the tweet
	Hashtags []Hashtag `json:"hashtags"`

	// Media Media attachments
	Media *[]Media `json:"media"`

	// Symbols Financial symbols in the tweet
	Symbols []Symbol `json:"symbols"`

	// Timestamps Timestamps in the tweet
	Timestamps *[]Timestamp `json:"timestamps"`

	// Urls URLs in the tweet
	Urls []Url `json:"urls"`

	// UserMentions User mentions in the tweet
	UserMentions []UserMention `json:"user_mentions"`
}

// TweetStats defines model for TweetStats.
type TweetStats struct {
	// BookmarkCount Number of bookmarks
	BookmarkCount int `json:"bookmark_count"`

	// FavoriteCount Number of likes/favorites
	FavoriteCount int `json:"favorite_count"`

	// QuoteCount Number of quote tweets
	QuoteCount int `json:"quote_count"`

	// ReplyCount Number of replies
	ReplyCount int `json:"reply_count"`

	// RetweetCount Number of retweets
	RetweetCount int `json:"retweet_count"`

	// ViewCount Number of views
	ViewCount *int `json:"view_count"`
}

// TweetUser defines model for TweetUser.
type TweetUser struct {
	// CreatedAt User account creation timestamp
	CreatedAt time.Time `json:"created_at"`

	// Description User bio/description
	Description string `json:"description"`

	// FollowersCount Number of followers
	FollowersCount int `json:"followers_count"`

	// FriendsCount Number of following
	FriendsCount int `json:"friends_count"`

	// Id User unique identifier
	Id string `json:"id"`

	// IsBlueVerified Whether user has blue verification
	IsBlueVerified bool `json:"is_blue_verified"`

	// Name User display name
	Name string `json:"name"`

	// ProfileImageUrl User profile image URL
	ProfileImageUrl string `json:"profile_image_url"`

	// RestId User REST API identifier
	RestId string `json:"rest_id"`

	// ScreenName User screen name (without @)
	ScreenName string `json:"screen_name"`

	// StatusesCount Number of tweets
	StatusesCount int `json:"statuses_count"`

	// Verified Whether user is verified
	Verified bool `json:"verified"`
}

// Url defines model for Url.
type Url struct {
	DisplayUrl  string  `json:"display_url"`
	ExpandedUrl *string `json:"expanded_url"`
	Indices     []int   `json:"indices"`
	Url         string  `json:"url"`
}

// UserMention defines model for UserMention.
type UserMention struct {
	// Id Mentioned user's unique identifier
	Id string `json:"id"`

	// Indices Start and end indices in the tweet text
	Indices []int `json:"indices"`

	// Name Mentioned user's display name
	Name string `json:"name"`

	// ScreenName Mentioned user's screen name (without @)
	ScreenName string `json:"screen_name"`
}

// PageLimit defines model for PageLimit.
type PageLimit = int

// PageOffset defines model for PageOffset.
type PageOffset = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetMentionsParams defines parameters for GetMentions.
type GetMentionsParams struct {
	// Limit Maximum number of items to return
	Limit *PageLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *PageOffset `form:"offset,omitempty" json:"offset,omitempty"`
}

func (p *GetMentionsParams) GetLimit() *PageLimit   { return p.Limit }
func (p *GetMentionsParams) GetOffset() *PageOffset { return p.Offset }

// GetQrcodeParams defines parameters for GetQrcode.
type GetQrcodeParams struct {
	// ThreadId The thread id to encode in the QR code
	ThreadId string `form:"thread_id" json:"thread_id"`
}

func (p *GetQrcodeParams) GetThreadId() string { return p.ThreadId }

// GetRenderParams defines parameters for GetRender.
type GetRenderParams struct {
	// ThreadId The thread id to render
	ThreadId string `form:"thread_id" json:"thread_id"`
}

func (p *GetRenderParams) GetThreadId() string { return p.ThreadId }
