openapi: 3.0.3
info:
  title: Threadmirror Backend API
  description: API for managing user profiles and follows
  version: 1.0.0
  contact:
    name: API Support
    url: https://github.com/example/threadmirror
servers:
  - url: http://localhost:8080/api/v1
    description: Development server
security:
  - bearerAuth: []

paths:
  /posts:
    get:
      summary: Get posts feed
      description: Get a paginated list of posts from followed users or public posts
      tags:
        - Posts
      parameters:
        - $ref: '#/components/parameters/PageLimit'
        - $ref: '#/components/parameters/PageOffset'
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                  meta:
                    $ref: "#/components/schemas/PaginationMeta"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /posts/{id}:
    get:
      summary: Get post details
      description: Get detailed information about a specific post
      tags:
        - Posts
      security: []
      parameters:
        - name: id
          in: path
          required: true
          description: Post ID
          schema:
            type: string
      responses:
        '200':
          description: Post details
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/PostDetails'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  # Bot endpoints
  /bot/stats:
    get:
      summary: Get bot statistics
      description: Get current bot statistics and status
      tags:
        - Bot
      security: []
      responses:
        '200':
          description: Bot statistics and status
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BotStats'
        '500':
          $ref: '#/components/responses/InternalServerError'


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PageLimit:
      name: limit
      in: query
      description: Maximum number of items to return
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    PageOffset:
      name: offset
      in: query
      description: Number of items to skip
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0

  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
          description: Post unique identifier
        content:
          type: string
          description: Post text content
          maxLength: 1000
        images:
          type: array
          items:
            type: object
            properties:
              image_id:
                type: string
                description: Image ID
            required:
              - image_id
          description: Post images
          maxItems: 9
        created_at:
          type: string
          format: date-time
          description: Post creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Post last update timestamp
      required:
        - id
        - content
        - images
        - created_at
        - updated_at

    PostDetails:
      type: object
      properties:
        id:
          type: string
          description: Post unique identifier
        content:
          type: string
          description: Post text content
        images:
          type: array
          items:
            type: object
            properties:
              image_id:
                type: string
                description: Image ID
            required:
              - image_id
          description: Post images
          maxItems: 9
        created_at:
          type: string
          format: date-time
          description: Post creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Post last update timestamp
      required:
        - id
        - content
        - images
        - created_at
        - updated_at


    Image:
      type: object
      properties:
        id:
          type: string
          description: Image unique identifier
          maxLength: 26
          nullable: true
        bucket:
          type: string
          description: Storage bucket name
      required:
        - bucket

    PaginationMeta:
      type: object
      properties:
        total:
          type: integer
          description: Total number of items
        limit:
          type: integer
          description: Maximum number of items returned
        offset:
          type: integer
          description: Number of items skipped
      required:
        - total
        - limit
        - offset

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
      required:
        - code
        - message

    BotStats:
      type: object
      properties:
        enabled:
          type: boolean
          description: Whether the bot is enabled
        username:
          type: string
          description: Bot's Twitter username
          nullable: true
        check_interval:
          type: string
          description: Bot's check interval (e.g., "5m0s")
        processed_count:
          type: integer
          description: Number of mentions processed
      required:
        - enabled
        - check_interval
        - processed_count


  responses:
    Unauthorized:
      description: Unauthorized - authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden - access denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
