/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotStats } from './BotStats';
import {
    BotStatsFromJSON,
    BotStatsFromJSONTyped,
    BotStatsToJSON,
    BotStatsToJSONTyped,
} from './BotStats';

/**
 * 
 * @export
 * @interface BotStatsGet200Response
 */
export interface BotStatsGet200Response {
    /**
     * 
     * @type {BotStats}
     * @memberof BotStatsGet200Response
     */
    data?: BotStats;
}

/**
 * Check if a given object implements the BotStatsGet200Response interface.
 */
export function instanceOfBotStatsGet200Response(value: object): value is BotStatsGet200Response {
    return true;
}

export function BotStatsGet200ResponseFromJSON(json: any): BotStatsGet200Response {
    return BotStatsGet200ResponseFromJSONTyped(json, false);
}

export function BotStatsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotStatsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : BotStatsFromJSON(json['data']),
    };
}

export function BotStatsGet200ResponseToJSON(json: any): BotStatsGet200Response {
    return BotStatsGet200ResponseToJSONTyped(json, false);
}

export function BotStatsGet200ResponseToJSONTyped(value?: BotStatsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BotStatsToJSON(value['data']),
    };
}

