/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupabaseConfig } from './SupabaseConfig';
import {
    SupabaseConfigFromJSON,
    SupabaseConfigFromJSONTyped,
    SupabaseConfigToJSON,
    SupabaseConfigToJSONTyped,
} from './SupabaseConfig';

/**
 * 
 * @export
 * @interface ConfigSupabaseGet200Response
 */
export interface ConfigSupabaseGet200Response {
    /**
     * 
     * @type {SupabaseConfig}
     * @memberof ConfigSupabaseGet200Response
     */
    data?: SupabaseConfig;
}

/**
 * Check if a given object implements the ConfigSupabaseGet200Response interface.
 */
export function instanceOfConfigSupabaseGet200Response(value: object): value is ConfigSupabaseGet200Response {
    return true;
}

export function ConfigSupabaseGet200ResponseFromJSON(json: any): ConfigSupabaseGet200Response {
    return ConfigSupabaseGet200ResponseFromJSONTyped(json, false);
}

export function ConfigSupabaseGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigSupabaseGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : SupabaseConfigFromJSON(json['data']),
    };
}

export function ConfigSupabaseGet200ResponseToJSON(json: any): ConfigSupabaseGet200Response {
    return ConfigSupabaseGet200ResponseToJSONTyped(json, false);
}

export function ConfigSupabaseGet200ResponseToJSONTyped(value?: ConfigSupabaseGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SupabaseConfigToJSON(value['data']),
    };
}

