/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Hashtag
 */
export interface Hashtag {
    /**
     * Hashtag text (without
     * @type {string}
     * @memberof Hashtag
     */
    text: string;
    /**
     * Start and end indices in the tweet text
     * @type {Array<number>}
     * @memberof Hashtag
     */
    indices: Array<number>;
}

/**
 * Check if a given object implements the Hashtag interface.
 */
export function instanceOfHashtag(value: object): value is Hashtag {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('indices' in value) || value['indices'] === undefined) return false;
    return true;
}

export function HashtagFromJSON(json: any): Hashtag {
    return HashtagFromJSONTyped(json, false);
}

export function HashtagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hashtag {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'indices': json['indices'],
    };
}

export function HashtagToJSON(json: any): Hashtag {
    return HashtagToJSONTyped(json, false);
}

export function HashtagToJSONTyped(value?: Hashtag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'indices': value['indices'],
    };
}

