/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthGet200Response
 */
export interface HealthGet200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthGet200Response
     */
    status: HealthGet200ResponseStatusEnum;
    /**
     * Current server time
     * @type {Date}
     * @memberof HealthGet200Response
     */
    timestamp: Date;
    /**
     * Service version
     * @type {string}
     * @memberof HealthGet200Response
     */
    version?: string;
}


/**
 * @export
 */
export const HealthGet200ResponseStatusEnum = {
    Ok: 'ok'
} as const;
export type HealthGet200ResponseStatusEnum = typeof HealthGet200ResponseStatusEnum[keyof typeof HealthGet200ResponseStatusEnum];


/**
 * Check if a given object implements the HealthGet200Response interface.
 */
export function instanceOfHealthGet200Response(value: object): value is HealthGet200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function HealthGet200ResponseFromJSON(json: any): HealthGet200Response {
    return HealthGet200ResponseFromJSONTyped(json, false);
}

export function HealthGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': (new Date(json['timestamp'])),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function HealthGet200ResponseToJSON(json: any): HealthGet200Response {
    return HealthGet200ResponseToJSONTyped(json, false);
}

export function HealthGet200ResponseToJSONTyped(value?: HealthGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': ((value['timestamp']).toISOString()),
        'version': value['version'],
    };
}

