/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthGet503Response
 */
export interface HealthGet503Response {
    /**
     * 
     * @type {string}
     * @memberof HealthGet503Response
     */
    status: HealthGet503ResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof HealthGet503Response
     */
    timestamp: Date;
    /**
     * Error message
     * @type {string}
     * @memberof HealthGet503Response
     */
    message: string;
}


/**
 * @export
 */
export const HealthGet503ResponseStatusEnum = {
    Error: 'error'
} as const;
export type HealthGet503ResponseStatusEnum = typeof HealthGet503ResponseStatusEnum[keyof typeof HealthGet503ResponseStatusEnum];


/**
 * Check if a given object implements the HealthGet503Response interface.
 */
export function instanceOfHealthGet503Response(value: object): value is HealthGet503Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function HealthGet503ResponseFromJSON(json: any): HealthGet503Response {
    return HealthGet503ResponseFromJSONTyped(json, false);
}

export function HealthGet503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthGet503Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': (new Date(json['timestamp'])),
        'message': json['message'],
    };
}

export function HealthGet503ResponseToJSON(json: any): HealthGet503Response {
    return HealthGet503ResponseToJSONTyped(json, false);
}

export function HealthGet503ResponseToJSONTyped(value?: HealthGet503Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': ((value['timestamp']).toISOString()),
        'message': value['message'],
    };
}

