/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaInfo
 */
export interface MediaInfo {
    /**
     * Media unique identifier
     * @type {string}
     * @memberof MediaInfo
     */
    id: string;
    /**
     * Media key identifier
     * @type {string}
     * @memberof MediaInfo
     */
    mediaKey: string;
    /**
     * Media type (photo, video, etc.)
     * @type {string}
     * @memberof MediaInfo
     */
    type: string;
    /**
     * Media URL
     * @type {string}
     * @memberof MediaInfo
     */
    url: string;
    /**
     * Display URL for media
     * @type {string}
     * @memberof MediaInfo
     */
    displayUrl: string;
    /**
     * Expanded URL for media
     * @type {string}
     * @memberof MediaInfo
     */
    expandedUrl: string;
    /**
     * Alternative text for accessibility
     * @type {string}
     * @memberof MediaInfo
     */
    altText?: string | null;
    /**
     * Media width in pixels
     * @type {number}
     * @memberof MediaInfo
     */
    width?: number | null;
    /**
     * Media height in pixels
     * @type {number}
     * @memberof MediaInfo
     */
    height?: number | null;
}

/**
 * Check if a given object implements the MediaInfo interface.
 */
export function instanceOfMediaInfo(value: object): value is MediaInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mediaKey' in value) || value['mediaKey'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('displayUrl' in value) || value['displayUrl'] === undefined) return false;
    if (!('expandedUrl' in value) || value['expandedUrl'] === undefined) return false;
    return true;
}

export function MediaInfoFromJSON(json: any): MediaInfo {
    return MediaInfoFromJSONTyped(json, false);
}

export function MediaInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'mediaKey': json['media_key'],
        'type': json['type'],
        'url': json['url'],
        'displayUrl': json['display_url'],
        'expandedUrl': json['expanded_url'],
        'altText': json['alt_text'] == null ? undefined : json['alt_text'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function MediaInfoToJSON(json: any): MediaInfo {
    return MediaInfoToJSONTyped(json, false);
}

export function MediaInfoToJSONTyped(value?: MediaInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'media_key': value['mediaKey'],
        'type': value['type'],
        'url': value['url'],
        'display_url': value['displayUrl'],
        'expanded_url': value['expandedUrl'],
        'alt_text': value['altText'],
        'width': value['width'],
        'height': value['height'],
    };
}

