/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
    UserProfileToJSONTyped,
} from './UserProfile';

/**
 * 
 * @export
 * @interface MeGet200Response
 */
export interface MeGet200Response {
    /**
     * 
     * @type {UserProfile}
     * @memberof MeGet200Response
     */
    data?: UserProfile;
}

/**
 * Check if a given object implements the MeGet200Response interface.
 */
export function instanceOfMeGet200Response(value: object): value is MeGet200Response {
    return true;
}

export function MeGet200ResponseFromJSON(json: any): MeGet200Response {
    return MeGet200ResponseFromJSONTyped(json, false);
}

export function MeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : UserProfileFromJSON(json['data']),
    };
}

export function MeGet200ResponseToJSON(json: any): MeGet200Response {
    return MeGet200ResponseToJSONTyped(json, false);
}

export function MeGet200ResponseToJSONTyped(value?: MeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UserProfileToJSON(value['data']),
    };
}

