/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThreadAuthor } from './ThreadAuthor';
import {
    ThreadAuthorFromJSON,
    ThreadAuthorFromJSONTyped,
    ThreadAuthorToJSON,
    ThreadAuthorToJSONTyped,
} from './ThreadAuthor';

/**
 * 
 * @export
 * @interface MentionSummary
 */
export interface MentionSummary {
    /**
     * Mention unique identifier
     * @type {string}
     * @memberof MentionSummary
     */
    id: string;
    /**
     * Content identifier (CID)
     * @type {string}
     * @memberof MentionSummary
     */
    cid: string;
    /**
     * Mention content preview/summary
     * @type {string}
     * @memberof MentionSummary
     */
    contentPreview: string;
    /**
     * Thread unique identifier
     * @type {string}
     * @memberof MentionSummary
     */
    threadId: string;
    /**
     * 
     * @type {ThreadAuthor}
     * @memberof MentionSummary
     */
    threadAuthor?: ThreadAuthor;
    /**
     * Mention creation timestamp
     * @type {Date}
     * @memberof MentionSummary
     */
    createdAt: Date;
    /**
     * Mention tweet creation timestamp
     * @type {Date}
     * @memberof MentionSummary
     */
    mentionCreateAt: Date;
    /**
     * Number of tweets in the thread
     * @type {number}
     * @memberof MentionSummary
     */
    numTweets: number;
}

/**
 * Check if a given object implements the MentionSummary interface.
 */
export function instanceOfMentionSummary(value: object): value is MentionSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('cid' in value) || value['cid'] === undefined) return false;
    if (!('contentPreview' in value) || value['contentPreview'] === undefined) return false;
    if (!('threadId' in value) || value['threadId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('mentionCreateAt' in value) || value['mentionCreateAt'] === undefined) return false;
    if (!('numTweets' in value) || value['numTweets'] === undefined) return false;
    return true;
}

export function MentionSummaryFromJSON(json: any): MentionSummary {
    return MentionSummaryFromJSONTyped(json, false);
}

export function MentionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MentionSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cid': json['cid'],
        'contentPreview': json['content_preview'],
        'threadId': json['thread_id'],
        'threadAuthor': json['thread_author'] == null ? undefined : ThreadAuthorFromJSON(json['thread_author']),
        'createdAt': (new Date(json['created_at'])),
        'mentionCreateAt': (new Date(json['mention_create_at'])),
        'numTweets': json['num_tweets'],
    };
}

export function MentionSummaryToJSON(json: any): MentionSummary {
    return MentionSummaryToJSONTyped(json, false);
}

export function MentionSummaryToJSONTyped(value?: MentionSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cid': value['cid'],
        'content_preview': value['contentPreview'],
        'thread_id': value['threadId'],
        'thread_author': ThreadAuthorToJSON(value['threadAuthor']),
        'created_at': ((value['createdAt']).toISOString()),
        'mention_create_at': ((value['mentionCreateAt']).toISOString()),
        'num_tweets': value['numTweets'],
    };
}

