/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MentionDetail } from './MentionDetail';
import {
    MentionDetailFromJSON,
    MentionDetailFromJSONTyped,
    MentionDetailToJSON,
    MentionDetailToJSONTyped,
} from './MentionDetail';

/**
 * 
 * @export
 * @interface MentionsIdGet200Response
 */
export interface MentionsIdGet200Response {
    /**
     * 
     * @type {MentionDetail}
     * @memberof MentionsIdGet200Response
     */
    data?: MentionDetail;
}

/**
 * Check if a given object implements the MentionsIdGet200Response interface.
 */
export function instanceOfMentionsIdGet200Response(value: object): value is MentionsIdGet200Response {
    return true;
}

export function MentionsIdGet200ResponseFromJSON(json: any): MentionsIdGet200Response {
    return MentionsIdGet200ResponseFromJSONTyped(json, false);
}

export function MentionsIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MentionsIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : MentionDetailFromJSON(json['data']),
    };
}

export function MentionsIdGet200ResponseToJSON(json: any): MentionsIdGet200Response {
    return MentionsIdGet200ResponseToJSONTyped(json, false);
}

export function MentionsIdGet200ResponseToJSONTyped(value?: MentionsIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MentionDetailToJSON(value['data']),
    };
}

