/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tweet } from './Tweet';
import {
    TweetFromJSON,
    TweetFromJSONTyped,
    TweetToJSON,
    TweetToJSONTyped,
} from './Tweet';
import type { MentionAuthor } from './MentionAuthor';
import {
    MentionAuthorFromJSON,
    MentionAuthorFromJSONTyped,
    MentionAuthorToJSON,
    MentionAuthorToJSONTyped,
} from './MentionAuthor';

/**
 * 
 * @export
 * @interface MentionDetail
 */
export interface MentionDetail {
    /**
     * Mention unique identifier
     * @type {string}
     * @memberof MentionDetail
     */
    id: string;
    /**
     * Content identifier (CID)
     * @type {string}
     * @memberof MentionDetail
     */
    cid: string;
    /**
     * Mention content preview/summary
     * @type {string}
     * @memberof MentionDetail
     */
    contentPreview: string;
    /**
     * 
     * @type {MentionAuthor}
     * @memberof MentionDetail
     */
    author?: MentionAuthor;
    /**
     * Mention creation timestamp
     * @type {Date}
     * @memberof MentionDetail
     */
    createdAt: Date;
    /**
     * Number of tweets in the thread
     * @type {number}
     * @memberof MentionDetail
     */
    numTweets: number;
    /**
     * Tweets associated with this mention
     * @type {Array<Tweet>}
     * @memberof MentionDetail
     */
    tweets: Array<Tweet> | null;
}

/**
 * Check if a given object implements the MentionDetail interface.
 */
export function instanceOfMentionDetail(value: object): value is MentionDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('cid' in value) || value['cid'] === undefined) return false;
    if (!('contentPreview' in value) || value['contentPreview'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('numTweets' in value) || value['numTweets'] === undefined) return false;
    if (!('tweets' in value) || value['tweets'] === undefined) return false;
    return true;
}

export function MentionDetailFromJSON(json: any): MentionDetail {
    return MentionDetailFromJSONTyped(json, false);
}

export function MentionDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): MentionDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cid': json['cid'],
        'contentPreview': json['content_preview'],
        'author': json['author'] == null ? undefined : MentionAuthorFromJSON(json['author']),
        'createdAt': (new Date(json['created_at'])),
        'numTweets': json['numTweets'],
        'tweets': (json['tweets'] == null ? null : (json['tweets'] as Array<any>).map(TweetFromJSON)),
    };
}

export function MentionDetailToJSON(json: any): MentionDetail {
    return MentionDetailToJSONTyped(json, false);
}

export function MentionDetailToJSONTyped(value?: MentionDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cid': value['cid'],
        'content_preview': value['contentPreview'],
        'author': MentionAuthorToJSON(value['author']),
        'created_at': ((value['createdAt']).toISOString()),
        'numTweets': value['numTweets'],
        'tweets': (value['tweets'] == null ? null : (value['tweets'] as Array<any>).map(TweetToJSON)),
    };
}

