/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NoteTweetRichTextTag } from './NoteTweetRichTextTag';
import {
    NoteTweetRichTextTagFromJSON,
    NoteTweetRichTextTagFromJSONTyped,
    NoteTweetRichTextTagToJSON,
    NoteTweetRichTextTagToJSONTyped,
} from './NoteTweetRichTextTag';

/**
 * 
 * @export
 * @interface NoteTweetRichText
 */
export interface NoteTweetRichText {
    /**
     * Richtext tag list defining formatting ranges
     * @type {Array<NoteTweetRichTextTag>}
     * @memberof NoteTweetRichText
     */
    richtextTags: Array<NoteTweetRichTextTag>;
}

/**
 * Check if a given object implements the NoteTweetRichText interface.
 */
export function instanceOfNoteTweetRichText(value: object): value is NoteTweetRichText {
    if (!('richtextTags' in value) || value['richtextTags'] === undefined) return false;
    return true;
}

export function NoteTweetRichTextFromJSON(json: any): NoteTweetRichText {
    return NoteTweetRichTextFromJSONTyped(json, false);
}

export function NoteTweetRichTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteTweetRichText {
    if (json == null) {
        return json;
    }
    return {
        
        'richtextTags': ((json['richtext_tags'] as Array<any>).map(NoteTweetRichTextTagFromJSON)),
    };
}

export function NoteTweetRichTextToJSON(json: any): NoteTweetRichText {
    return NoteTweetRichTextToJSONTyped(json, false);
}

export function NoteTweetRichTextToJSONTyped(value?: NoteTweetRichText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'richtext_tags': ((value['richtextTags'] as Array<any>).map(NoteTweetRichTextTagToJSON)),
    };
}

