/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImagesInner
 */
export interface PostImagesInner {
    /**
     * Image ID
     * @type {string}
     * @memberof PostImagesInner
     */
    imageId: string;
}

/**
 * Check if a given object implements the PostImagesInner interface.
 */
export function instanceOfPostImagesInner(value: object): value is PostImagesInner {
    if (!('imageId' in value) || value['imageId'] === undefined) return false;
    return true;
}

export function PostImagesInnerFromJSON(json: any): PostImagesInner {
    return PostImagesInnerFromJSONTyped(json, false);
}

export function PostImagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['image_id'],
    };
}

export function PostImagesInnerToJSON(json: any): PostImagesInner {
    return PostImagesInnerToJSONTyped(json, false);
}

export function PostImagesInnerToJSONTyped(value?: PostImagesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_id': value['imageId'],
    };
}

