/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAuthor } from './PostAuthor';
import {
    PostAuthorFromJSON,
    PostAuthorFromJSONTyped,
    PostAuthorToJSON,
    PostAuthorToJSONTyped,
} from './PostAuthor';
import type { Tweet } from './Tweet';
import {
    TweetFromJSON,
    TweetFromJSONTyped,
    TweetToJSON,
    TweetToJSONTyped,
} from './Tweet';

/**
 * 
 * @export
 * @interface PostDetail
 */
export interface PostDetail {
    /**
     * Post unique identifier
     * @type {string}
     * @memberof PostDetail
     */
    id: string;
    /**
     * Content identifier (CID)
     * @type {string}
     * @memberof PostDetail
     */
    cid: string;
    /**
     * Post content preview/summary
     * @type {string}
     * @memberof PostDetail
     */
    contentPreview: string;
    /**
     * 
     * @type {PostAuthor}
     * @memberof PostDetail
     */
    author?: PostAuthor;
    /**
     * Post creation timestamp
     * @type {Date}
     * @memberof PostDetail
     */
    createdAt: Date;
    /**
     * Number of tweets in the thread
     * @type {number}
     * @memberof PostDetail
     */
    numTweets: number;
    /**
     * Tweets associated with this post
     * @type {Array<Tweet>}
     * @memberof PostDetail
     */
    tweets: Array<Tweet> | null;
}

/**
 * Check if a given object implements the PostDetail interface.
 */
export function instanceOfPostDetail(value: object): value is PostDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('cid' in value) || value['cid'] === undefined) return false;
    if (!('contentPreview' in value) || value['contentPreview'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('numTweets' in value) || value['numTweets'] === undefined) return false;
    if (!('tweets' in value) || value['tweets'] === undefined) return false;
    return true;
}

export function PostDetailFromJSON(json: any): PostDetail {
    return PostDetailFromJSONTyped(json, false);
}

export function PostDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cid': json['cid'],
        'contentPreview': json['content_preview'],
        'author': json['author'] == null ? undefined : PostAuthorFromJSON(json['author']),
        'createdAt': (new Date(json['created_at'])),
        'numTweets': json['numTweets'],
        'tweets': (json['tweets'] == null ? null : (json['tweets'] as Array<any>).map(TweetFromJSON)),
    };
}

export function PostDetailToJSON(json: any): PostDetail {
    return PostDetailToJSONTyped(json, false);
}

export function PostDetailToJSONTyped(value?: PostDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cid': value['cid'],
        'content_preview': value['contentPreview'],
        'author': PostAuthorToJSON(value['author']),
        'created_at': ((value['createdAt']).toISOString()),
        'numTweets': value['numTweets'],
        'tweets': (value['tweets'] == null ? null : (value['tweets'] as Array<any>).map(TweetToJSON)),
    };
}

