/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAuthor } from './PostAuthor';
import {
    PostAuthorFromJSON,
    PostAuthorFromJSONTyped,
    PostAuthorToJSON,
    PostAuthorToJSONTyped,
} from './PostAuthor';
import type { Tweet } from './Tweet';
import {
    TweetFromJSON,
    TweetFromJSONTyped,
    TweetToJSON,
    TweetToJSONTyped,
} from './Tweet';

/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * Post unique identifier
     * @type {string}
     * @memberof Post
     */
    id: string;
    /**
     * Post content preview/summary
     * @type {string}
     * @memberof Post
     */
    contentPreview: string;
    /**
     * 
     * @type {PostAuthor}
     * @memberof Post
     */
    author?: PostAuthor;
    /**
     * Post creation timestamp
     * @type {Date}
     * @memberof Post
     */
    createdAt: Date;
    /**
     * Thread tweets associated with this post
     * @type {Array<Tweet>}
     * @memberof Post
     */
    threads?: Array<Tweet> | null;
}

/**
 * Check if a given object implements the Post interface.
 */
export function instanceOfPost(value: object): value is Post {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contentPreview' in value) || value['contentPreview'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PostFromJSON(json: any): Post {
    return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Post {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'contentPreview': json['content_preview'],
        'author': json['author'] == null ? undefined : PostAuthorFromJSON(json['author']),
        'createdAt': (new Date(json['created_at'])),
        'threads': json['threads'] == null ? undefined : ((json['threads'] as Array<any>).map(TweetFromJSON)),
    };
}

export function PostToJSON(json: any): Post {
    return PostToJSONTyped(json, false);
}

export function PostToJSONTyped(value?: Post | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content_preview': value['contentPreview'],
        'author': PostAuthorToJSON(value['author']),
        'created_at': ((value['createdAt']).toISOString()),
        'threads': value['threads'] == null ? undefined : ((value['threads'] as Array<any>).map(TweetToJSON)),
    };
}

