/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostSummary } from './PostSummary';
import {
    PostSummaryFromJSON,
    PostSummaryFromJSONTyped,
    PostSummaryToJSON,
    PostSummaryToJSONTyped,
} from './PostSummary';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface PostsGet200Response
 */
export interface PostsGet200Response {
    /**
     * 
     * @type {Array<PostSummary>}
     * @memberof PostsGet200Response
     */
    data?: Array<PostSummary>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PostsGet200Response
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the PostsGet200Response interface.
 */
export function instanceOfPostsGet200Response(value: object): value is PostsGet200Response {
    return true;
}

export function PostsGet200ResponseFromJSON(json: any): PostsGet200Response {
    return PostsGet200ResponseFromJSONTyped(json, false);
}

export function PostsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PostSummaryFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function PostsGet200ResponseToJSON(json: any): PostsGet200Response {
    return PostsGet200ResponseToJSONTyped(json, false);
}

export function PostsGet200ResponseToJSONTyped(value?: PostsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PostSummaryToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

