/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAuthor
 */
export interface PostAuthor {
    /**
     * Author's unique identifier (Twitter user ID)
     * @type {string}
     * @memberof PostAuthor
     */
    id: string;
    /**
     * Author's display name
     * @type {string}
     * @memberof PostAuthor
     */
    name: string;
    /**
     * Author's screen name (without @)
     * @type {string}
     * @memberof PostAuthor
     */
    screenName: string;
    /**
     * Author's profile image URL
     * @type {string}
     * @memberof PostAuthor
     */
    profileImageUrl: string;
}

/**
 * Check if a given object implements the PostAuthor interface.
 */
export function instanceOfPostAuthor(value: object): value is PostAuthor {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('screenName' in value) || value['screenName'] === undefined) return false;
    if (!('profileImageUrl' in value) || value['profileImageUrl'] === undefined) return false;
    return true;
}

export function PostAuthorFromJSON(json: any): PostAuthor {
    return PostAuthorFromJSONTyped(json, false);
}

export function PostAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAuthor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'screenName': json['screen_name'],
        'profileImageUrl': json['profile_image_url'],
    };
}

export function PostAuthorToJSON(json: any): PostAuthor {
    return PostAuthorToJSONTyped(json, false);
}

export function PostAuthorToJSONTyped(value?: PostAuthor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'screen_name': value['screenName'],
        'profile_image_url': value['profileImageUrl'],
    };
}

