/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDetails } from './PostDetails';
import {
    PostDetailsFromJSON,
    PostDetailsFromJSONTyped,
    PostDetailsToJSON,
    PostDetailsToJSONTyped,
} from './PostDetails';

/**
 * 
 * @export
 * @interface PostsIdGet200Response
 */
export interface PostsIdGet200Response {
    /**
     * 
     * @type {PostDetails}
     * @memberof PostsIdGet200Response
     */
    data?: PostDetails;
}

/**
 * Check if a given object implements the PostsIdGet200Response interface.
 */
export function instanceOfPostsIdGet200Response(value: object): value is PostsIdGet200Response {
    return true;
}

export function PostsIdGet200ResponseFromJSON(json: any): PostsIdGet200Response {
    return PostsIdGet200ResponseFromJSONTyped(json, false);
}

export function PostsIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostsIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : PostDetailsFromJSON(json['data']),
    };
}

export function PostsIdGet200ResponseToJSON(json: any): PostsIdGet200Response {
    return PostsIdGet200ResponseToJSONTyped(json, false);
}

export function PostsIdGet200ResponseToJSONTyped(value?: PostsIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PostDetailsToJSON(value['data']),
    };
}

