/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Storage bucket names configuration
 * @export
 * @interface SupabaseConfigBucketNames
 */
export interface SupabaseConfigBucketNames {
    /**
     * post images bucket name
     * @type {string}
     * @memberof SupabaseConfigBucketNames
     */
    postImages: string;
}

/**
 * Check if a given object implements the SupabaseConfigBucketNames interface.
 */
export function instanceOfSupabaseConfigBucketNames(value: object): value is SupabaseConfigBucketNames {
    if (!('postImages' in value) || value['postImages'] === undefined) return false;
    return true;
}

export function SupabaseConfigBucketNamesFromJSON(json: any): SupabaseConfigBucketNames {
    return SupabaseConfigBucketNamesFromJSONTyped(json, false);
}

export function SupabaseConfigBucketNamesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupabaseConfigBucketNames {
    if (json == null) {
        return json;
    }
    return {
        
        'postImages': json['post_images'],
    };
}

export function SupabaseConfigBucketNamesToJSON(json: any): SupabaseConfigBucketNames {
    return SupabaseConfigBucketNamesToJSONTyped(json, false);
}

export function SupabaseConfigBucketNamesToJSONTyped(value?: SupabaseConfigBucketNames | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post_images': value['postImages'],
    };
}

