/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Symbol
 */
export interface Symbol {
    /**
     * Symbol text (without $)
     * @type {string}
     * @memberof Symbol
     */
    text: string;
    /**
     * Start and end indices in the tweet text
     * @type {Array<number>}
     * @memberof Symbol
     */
    indices: Array<number>;
}

/**
 * Check if a given object implements the Symbol interface.
 */
export function instanceOfSymbol(value: object): value is Symbol {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('indices' in value) || value['indices'] === undefined) return false;
    return true;
}

export function SymbolFromJSON(json: any): Symbol {
    return SymbolFromJSONTyped(json, false);
}

export function SymbolFromJSONTyped(json: any, ignoreDiscriminator: boolean): Symbol {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'indices': json['indices'],
    };
}

export function SymbolToJSON(json: any): Symbol {
    return SymbolToJSONTyped(json, false);
}

export function SymbolToJSONTyped(value?: Symbol | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'indices': value['indices'],
    };
}

