/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThreadScrapePost200Response
 */
export interface ThreadScrapePost200Response {
    /**
     * Twitter tweet ID extracted from the URL
     * @type {string}
     * @memberof ThreadScrapePost200Response
     */
    tweetId: string;
    /**
     * Success message
     * @type {string}
     * @memberof ThreadScrapePost200Response
     */
    message: string;
}

/**
 * Check if a given object implements the ThreadScrapePost200Response interface.
 */
export function instanceOfThreadScrapePost200Response(value: object): value is ThreadScrapePost200Response {
    if (!('tweetId' in value) || value['tweetId'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ThreadScrapePost200ResponseFromJSON(json: any): ThreadScrapePost200Response {
    return ThreadScrapePost200ResponseFromJSONTyped(json, false);
}

export function ThreadScrapePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadScrapePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tweetId': json['tweet_id'],
        'message': json['message'],
    };
}

export function ThreadScrapePost200ResponseToJSON(json: any): ThreadScrapePost200Response {
    return ThreadScrapePost200ResponseToJSONTyped(json, false);
}

export function ThreadScrapePost200ResponseToJSONTyped(value?: ThreadScrapePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tweet_id': value['tweetId'],
        'message': value['message'],
    };
}

