/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThreadDetail } from './ThreadDetail';
import {
    ThreadDetailFromJSON,
    ThreadDetailFromJSONTyped,
    ThreadDetailToJSON,
    ThreadDetailToJSONTyped,
} from './ThreadDetail';

/**
 * 
 * @export
 * @interface ThreadIdGet200Response
 */
export interface ThreadIdGet200Response {
    /**
     * 
     * @type {ThreadDetail}
     * @memberof ThreadIdGet200Response
     */
    data?: ThreadDetail;
}

/**
 * Check if a given object implements the ThreadIdGet200Response interface.
 */
export function instanceOfThreadIdGet200Response(value: object): value is ThreadIdGet200Response {
    return true;
}

export function ThreadIdGet200ResponseFromJSON(json: any): ThreadIdGet200Response {
    return ThreadIdGet200ResponseFromJSONTyped(json, false);
}

export function ThreadIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ThreadDetailFromJSON(json['data']),
    };
}

export function ThreadIdGet200ResponseToJSON(json: any): ThreadIdGet200Response {
    return ThreadIdGet200ResponseToJSONTyped(json, false);
}

export function ThreadIdGet200ResponseToJSONTyped(value?: ThreadIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ThreadDetailToJSON(value['data']),
    };
}

