/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tweet } from './Tweet';
import {
    TweetFromJSON,
    TweetFromJSONTyped,
    TweetToJSON,
    TweetToJSONTyped,
} from './Tweet';

/**
 * 
 * @export
 * @interface ThreadDetail
 */
export interface ThreadDetail {
    /**
     * Thread unique identifier
     * @type {string}
     * @memberof ThreadDetail
     */
    id: string;
    /**
     * Content identifier (CID)
     * @type {string}
     * @memberof ThreadDetail
     */
    cid: string;
    /**
     * Thread content preview/summary
     * @type {string}
     * @memberof ThreadDetail
     */
    contentPreview: string;
    /**
     * Thread creation timestamp
     * @type {Date}
     * @memberof ThreadDetail
     */
    createdAt: Date;
    /**
     * Number of tweets in the thread
     * @type {number}
     * @memberof ThreadDetail
     */
    numTweets: number;
    /**
     * Tweets associated with this Thread
     * @type {Array<Tweet>}
     * @memberof ThreadDetail
     */
    tweets: Array<Tweet> | null;
}

/**
 * Check if a given object implements the ThreadDetail interface.
 */
export function instanceOfThreadDetail(value: object): value is ThreadDetail {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('cid' in value) || value['cid'] === undefined) return false;
    if (!('contentPreview' in value) || value['contentPreview'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('numTweets' in value) || value['numTweets'] === undefined) return false;
    if (!('tweets' in value) || value['tweets'] === undefined) return false;
    return true;
}

export function ThreadDetailFromJSON(json: any): ThreadDetail {
    return ThreadDetailFromJSONTyped(json, false);
}

export function ThreadDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cid': json['cid'],
        'contentPreview': json['content_preview'],
        'createdAt': (new Date(json['created_at'])),
        'numTweets': json['num_tweets'],
        'tweets': (json['tweets'] == null ? null : (json['tweets'] as Array<any>).map(TweetFromJSON)),
    };
}

export function ThreadDetailToJSON(json: any): ThreadDetail {
    return ThreadDetailToJSONTyped(json, false);
}

export function ThreadDetailToJSONTyped(value?: ThreadDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cid': value['cid'],
        'content_preview': value['contentPreview'],
        'created_at': ((value['createdAt']).toISOString()),
        'num_tweets': value['numTweets'],
        'tweets': (value['tweets'] == null ? null : (value['tweets'] as Array<any>).map(TweetToJSON)),
    };
}

