/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThreadScrapePostRequest
 */
export interface ThreadScrapePostRequest {
    /**
     * Twitter/X URL to scrape (e.g., https://twitter.com/user/status/123456789)
     * @type {string}
     * @memberof ThreadScrapePostRequest
     */
    url: string;
}

/**
 * Check if a given object implements the ThreadScrapePostRequest interface.
 */
export function instanceOfThreadScrapePostRequest(value: object): value is ThreadScrapePostRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ThreadScrapePostRequestFromJSON(json: any): ThreadScrapePostRequest {
    return ThreadScrapePostRequestFromJSONTyped(json, false);
}

export function ThreadScrapePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadScrapePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function ThreadScrapePostRequestToJSON(json: any): ThreadScrapePostRequest {
    return ThreadScrapePostRequestToJSONTyped(json, false);
}

export function ThreadScrapePostRequestToJSONTyped(value?: ThreadScrapePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

