/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Timestamp
 */
export interface Timestamp {
    /**
     * Start and end indices in the text
     * @type {Array<number>}
     * @memberof Timestamp
     */
    indices: Array<number>;
    /**
     * Seconds value of timestamp
     * @type {number}
     * @memberof Timestamp
     */
    seconds: number;
    /**
     * Timestamp text
     * @type {string}
     * @memberof Timestamp
     */
    text: string;
}

/**
 * Check if a given object implements the Timestamp interface.
 */
export function instanceOfTimestamp(value: object): value is Timestamp {
    if (!('indices' in value) || value['indices'] === undefined) return false;
    if (!('seconds' in value) || value['seconds'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function TimestampFromJSON(json: any): Timestamp {
    return TimestampFromJSONTyped(json, false);
}

export function TimestampFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timestamp {
    if (json == null) {
        return json;
    }
    return {
        
        'indices': json['indices'],
        'seconds': json['seconds'],
        'text': json['text'],
    };
}

export function TimestampToJSON(json: any): Timestamp {
    return TimestampToJSONTyped(json, false);
}

export function TimestampToJSONTyped(value?: Timestamp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'indices': value['indices'],
        'seconds': value['seconds'],
        'text': value['text'],
    };
}

