/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserMention
 */
export interface UserMention {
    /**
     * Mentioned user's unique identifier
     * @type {string}
     * @memberof UserMention
     */
    id: string;
    /**
     * Mentioned user's screen name (without @)
     * @type {string}
     * @memberof UserMention
     */
    screenName: string;
    /**
     * Mentioned user's display name
     * @type {string}
     * @memberof UserMention
     */
    name: string;
    /**
     * Start and end indices in the tweet text
     * @type {Array<number>}
     * @memberof UserMention
     */
    indices: Array<number>;
}

/**
 * Check if a given object implements the UserMention interface.
 */
export function instanceOfUserMention(value: object): value is UserMention {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('screenName' in value) || value['screenName'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('indices' in value) || value['indices'] === undefined) return false;
    return true;
}

export function UserMentionFromJSON(json: any): UserMention {
    return UserMentionFromJSONTyped(json, false);
}

export function UserMentionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMention {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'screenName': json['screen_name'],
        'name': json['name'],
        'indices': json['indices'],
    };
}

export function UserMentionToJSON(json: any): UserMention {
    return UserMentionToJSONTyped(json, false);
}

export function UserMentionToJSONTyped(value?: UserMention | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'screen_name': value['screenName'],
        'name': value['name'],
        'indices': value['indices'],
    };
}

