/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileSummary
 */
export interface UserProfileSummary {
    /**
     * User unique identifier
     * @type {string}
     * @memberof UserProfileSummary
     */
    userId: string;
    /**
     * User public display ID
     * @type {string}
     * @memberof UserProfileSummary
     */
    displayId: string;
    /**
     * User display name
     * @type {string}
     * @memberof UserProfileSummary
     */
    nickname: string;
    /**
     * User biography/signature (truncated)
     * @type {string}
     * @memberof UserProfileSummary
     */
    bio?: string | null;
}

/**
 * Check if a given object implements the UserProfileSummary interface.
 */
export function instanceOfUserProfileSummary(value: object): value is UserProfileSummary {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('displayId' in value) || value['displayId'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    return true;
}

export function UserProfileSummaryFromJSON(json: any): UserProfileSummary {
    return UserProfileSummaryFromJSONTyped(json, false);
}

export function UserProfileSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'displayId': json['display_id'],
        'nickname': json['nickname'],
        'bio': json['bio'] == null ? undefined : json['bio'],
    };
}

export function UserProfileSummaryToJSON(json: any): UserProfileSummary {
    return UserProfileSummaryToJSONTyped(json, false);
}

export function UserProfileSummaryToJSONTyped(value?: UserProfileSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'display_id': value['displayId'],
        'nickname': value['nickname'],
        'bio': value['bio'],
    };
}

