// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_generated

import (
	"context"
)

type Querier interface {
	CountBotCookies(ctx context.Context) (int64, error)
	CountMentions(ctx context.Context, arg CountMentionsParams) (int64, error)
	CountMentionsByUser(ctx context.Context, arg CountMentionsByUserParams) (int64, error)
	CreateBotCookie(ctx context.Context, arg CreateBotCookieParams) (BotCookie, error)
	CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error)
	CreateProcessedMark(ctx context.Context, arg CreateProcessedMarkParams) (ProcessedMark, error)
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	DeleteOldProcessedMarks(ctx context.Context, arg DeleteOldProcessedMarksParams) error
	DeleteProcessedMark(ctx context.Context, arg DeleteProcessedMarkParams) error
	GetBotCookieByEmailAndUsername(ctx context.Context, arg GetBotCookieByEmailAndUsernameParams) (BotCookie, error)
	// BotCookie queries
	GetBotCookieByID(ctx context.Context, arg GetBotCookieByIDParams) (BotCookie, error)
	GetFailedThreadsForRetry(ctx context.Context, arg GetFailedThreadsForRetryParams) ([]Thread, error)
	// Mention queries
	GetMentionByID(ctx context.Context, arg GetMentionByIDParams) (GetMentionByIDRow, error)
	GetMentionByUserIDAndThreadID(ctx context.Context, arg GetMentionByUserIDAndThreadIDParams) (GetMentionByUserIDAndThreadIDRow, error)
	GetMentions(ctx context.Context, arg GetMentionsParams) ([]GetMentionsRow, error)
	GetMentionsByUser(ctx context.Context, arg GetMentionsByUserParams) ([]GetMentionsByUserRow, error)
	GetOldPendingThreads(ctx context.Context, arg GetOldPendingThreadsParams) ([]Thread, error)
	// ProcessedMark queries
	GetProcessedMark(ctx context.Context, arg GetProcessedMarkParams) (ProcessedMark, error)
	GetStuckScrapingThreads(ctx context.Context, arg GetStuckScrapingThreadsParams) ([]Thread, error)
	// Thread queries
	GetThreadByID(ctx context.Context, arg GetThreadByIDParams) (Thread, error)
	GetThreadsByIDs(ctx context.Context, arg GetThreadsByIDsParams) ([]Thread, error)
	IncrementThreadRetryCount(ctx context.Context, arg IncrementThreadRetryCountParams) error
	ListBotCookies(ctx context.Context, arg ListBotCookiesParams) ([]BotCookie, error)
	SoftDeleteBotCookie(ctx context.Context, arg SoftDeleteBotCookieParams) error
	UpdateBotCookie(ctx context.Context, arg UpdateBotCookieParams) error
	UpdateMention(ctx context.Context, arg UpdateMentionParams) error
	UpdateThreadComplete(ctx context.Context, arg UpdateThreadCompleteParams) error
	UpdateThreadStatus(ctx context.Context, arg UpdateThreadStatusParams) error
	UpsertProcessedMark(ctx context.Context, arg UpsertProcessedMarkParams) (ProcessedMark, error)
}

var _ Querier = (*Queries)(nil)
