openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /graphql/{pathQueryId}/HomeTimeline:
    get:
      operationId: getHomeTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimelineResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/HomeLatestTimeline:
    get:
      operationId: getHomeLatestTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimelineResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/ListLatestTweetsTimeline:
    get:
      operationId: getListLatestTweetsTimeline
      description: get tweet list of timeline
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListLatestTweetsTimelineResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/SearchTimeline:
    get:
      operationId: getSearchTimeline
      description: search tweet list. product:[Top, Latest, People, Photos, Videos]
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchTimelineResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/CommunityTweetsTimeline:
    get:
      operationId: getCommunityTweetsTimeline
      description: get tweet list of community. rankingMode:[Recency, Relevance]
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommunityTweetsTimelineResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/CommunityMediaTimeline:
    get:
      operationId: getCommunityMediaTimeline
      description: get media list of community
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommunityMediaTimelineResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/CommunityAboutTimeline:
    get:
      operationId: getCommunityAboutTimeline
      description: get about of community
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommunityAboutTimelineResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/NotificationsTimeline:
    get:
      operationId: getNotificationsTimeline
      description: get notification list. timeline_type:[All, Verified, Mentions]
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationsTimelineResponse"
      tags:
        - "tweet"

components:
  schemas:
    TimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/HomeTimelineResponseData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    HomeTimelineResponseData:
      required:
        - "home"
      properties:
        home:
          $ref: "#/components/schemas/HomeTimelineHome"

    HomeTimelineHome:
      required:
        - "home_timeline_urt"
      properties:
        home_timeline_urt:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"

    ListLatestTweetsTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/ListTweetsTimelineData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    ListTweetsTimelineData:
      required:
        - "list"
      properties:
        list:
          $ref: "#/components/schemas/ListTweetsTimelineList"

    ListTweetsTimelineList:
      required:
        - "tweets_timeline"
      properties:
        tweets_timeline:
          $ref: "#/components/schemas/TimelineResult"

    SearchTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/SearchTimelineData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    SearchTimelineData:
      required:
        - "search_by_raw_query"
      properties:
        search_by_raw_query:
          $ref: "#/components/schemas/SearchByRawQuery"

    SearchByRawQuery:
      required:
        - "search_timeline"
      properties:
        search_timeline:
          $ref: "#/components/schemas/SearchTimeline"

    SearchTimeline:
      required:
        - "timeline"
      properties:
        timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"

    CommunityTweetsTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/RankedCommunityTweetData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    RankedCommunityTweetData:
      required:
        - "communityResults"
      properties:
        communityResults:
          $ref: "#/components/schemas/RankedCommunityResults"

    RankedCommunityResults:
      required:
        - "result"
      properties:
        result:
          $ref: "#/components/schemas/RankedCommunityResult"

    RankedCommunityResult:
      required:
        - "__typename"
        - "ranked_community_timeline"
      properties:
        __typename:
          $ref: "./../schemas/typename.yaml#/components/schemas/TypeName" # Community
        ranked_community_timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/TimelineResult"

    CommunityMediaTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/MediaCommunityTweetData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    MediaCommunityTweetData:
      required:
        - "__typename"
        - "communityResults"
      properties:
        communityResults:
          $ref: "#/components/schemas/MediaCommunityResults"

    MediaCommunityResults:
      required:
        - "result"
      properties:
        result:
          $ref: "#/components/schemas/MediaCommunityResult"

    MediaCommunityResult:
      required:
        - "__typename"
        - "community_media_timeline"
      properties:
        __typename:
          $ref: "./../schemas/typename.yaml#/components/schemas/TypeName" # Community
        community_media_timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/TimelineResult"

    CommunityAboutTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/AboutCommunityTweetData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    AboutCommunityTweetData:
      required:
        - "communityResults"
      properties:
        communityResults:
          $ref: "#/components/schemas/AboutCommunityResults"

    AboutCommunityResults:
      required:
        - "result"
      properties:
        result:
          $ref: "#/components/schemas/AboutCommunityResult"

    AboutCommunityResult:
      required:
        - "__typename"
        - "about_timeline"
      properties:
        __typename:
          $ref: "./../schemas/typename.yaml#/components/schemas/TypeName" # Community
        about_timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/TimelineResult"

    NotificationsTimelineResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/NotificationsTimelineData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    NotificationsTimelineData:
      required:
        - "viewer_v2"
      properties:
        viewer_v2:
          $ref: "#/components/schemas/NotificationsViewerV2"

    NotificationsViewerV2:
      required:
        - "user_results"
      properties:
        user_results:
          $ref: "#/components/schemas/NotificationsUserResults"

    NotificationsUserResults:
      required:
        - "result"
      properties:
        result:
          $ref: "#/components/schemas/NotificationsResult"

    NotificationsResult:
      required:
        - "__typename"
        - "rest_id"
        - "notification_timeline"
      properties:
        __typename:
          $ref: "./../schemas/typename.yaml#/components/schemas/TypeName" # User
        rest_id:
          type: string
          pattern: "^[0-9]+$"
        notification_timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/TimelineResult"
