openapi: 3.0.3
info:
  title: Twitter OpenAPI
  version: 0.0.1

paths:
  /graphql/{pathQueryId}/UserTweets:
    get:
      operationId: getUserTweets
      description: "get user tweets"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserTweetsResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/UserTweetsAndReplies:
    get:
      operationId: getUserTweetsAndReplies
      description: "get user replies tweets"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserTweetsResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/UserHighlightsTweets:
    get:
      operationId: getUserHighlightsTweets
      description: "get user highlights tweets"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserHighlightsTweetsResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/UserMedia:
    get:
      operationId: getUserMedia
      description: "get user media tweets"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserTweetsResponse"
      tags:
        - "tweet"

  /graphql/{pathQueryId}/Likes:
    get:
      operationId: getLikes
      description: "get user likes tweets"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserTweetsResponse"
      tags:
        - "tweet"

components:
  schemas:
    UserTweetsResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/UserTweetsData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    UserTweetsData:
      properties:
        user:
          $ref: "#/components/schemas/UserTweetsUser"

    UserTweetsUser:
      required:
        - "result"
      properties:
        result:
          $ref: "#/components/schemas/UserTweetsResultV1"

    UserTweetsResultV1:
      required:
        - "__typename"
        - "timeline"
      properties:
        __typename:
          $ref: "./../schemas/typename.yaml#/components/schemas/TypeName" # User
        timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/TimelineResult"

    UserTweetsResultV2:
      required:
        - "__typename"
        - "timeline_v2"
      properties:
        __typename:
          $ref: "./../schemas/typename.yaml#/components/schemas/TypeName" # User
        timeline_v2:
          $ref: "./../schemas/timeline.yaml#/components/schemas/TimelineResult"

    UserHighlightsTweetsResponse:
      required:
        - "data"
      properties:
        data:
          $ref: "#/components/schemas/UserHighlightsTweetsData"
        errors:
          type: array
          items:
            $ref: "./../response/error.yaml#/components/schemas/ErrorResponse"

    UserHighlightsTweetsData:
      properties:
        user:
          $ref: "#/components/schemas/UserHighlightsTweetsUser"

    UserHighlightsTweetsUser:
      required:
        - "result"
      properties:
        result:
          $ref: "#/components/schemas/UserHighlightsTweetsResult"

    UserHighlightsTweetsResult:
      required:
        - "timeline"
        - "__typename"
      properties:
        timeline:
          $ref: "#/components/schemas/UserHighlightsTweetsTimeline"
        __typename:
          $ref: "./../schemas/typename.yaml#/components/schemas/TypeName" # User

    UserHighlightsTweetsTimeline:
      required:
        - "timeline"
      properties:
        timeline:
          $ref: "./../schemas/timeline.yaml#/components/schemas/Timeline"
