/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BotStatsGet200Response,
} from '../models/index';
import {
    BotStatsGet200ResponseFromJSON,
    BotStatsGet200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class BotApi extends runtime.BaseAPI {

    /**
     * Get current bot statistics and status
     * Get bot statistics
     */
    async botStatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BotStatsGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bot/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BotStatsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current bot statistics and status
     * Get bot statistics
     */
    async botStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BotStatsGet200Response> {
        const response = await this.botStatsGetRaw(initOverrides);
        return await response.value();
    }

}
