/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfigSupabaseGet200Response,
} from '../models/index';
import {
    ConfigSupabaseGet200ResponseFromJSON,
    ConfigSupabaseGet200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class ConfigApi extends runtime.BaseAPI {

    /**
     * Retrieve Supabase configuration for client-side initialization
     * Get Supabase configuration
     */
    async configSupabaseGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigSupabaseGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/config/supabase`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigSupabaseGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve Supabase configuration for client-side initialization
     * Get Supabase configuration
     */
    async configSupabaseGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigSupabaseGet200Response> {
        const response = await this.configSupabaseGetRaw(initOverrides);
        return await response.value();
    }

}
