/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MentionsGet200Response,
} from '../models/index';
import {
    MentionsGet200ResponseFromJSON,
    MentionsGet200ResponseToJSON,
} from '../models/index';

export interface MentionsGetRequest {
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class MentionsApi extends runtime.BaseAPI {

    /**
     * Get a paginated list of mentions from followed users or public mentions
     * Get mentions feed
     */
    async mentionsGetRaw(requestParameters: MentionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MentionsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/mentions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MentionsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of mentions from followed users or public mentions
     * Get mentions feed
     */
    async mentionsGet(requestParameters: MentionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MentionsGet200Response> {
        const response = await this.mentionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
