/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostsGet200Response,
  PostsIdGet200Response,
} from '../models/index';
import {
    PostsGet200ResponseFromJSON,
    PostsGet200ResponseToJSON,
    PostsIdGet200ResponseFromJSON,
    PostsIdGet200ResponseToJSON,
} from '../models/index';

export interface PostsGetRequest {
    limit?: number;
    offset?: number;
}

export interface PostsIdGetRequest {
    id: string;
}

/**
 * 
 */
export class PostsApi extends runtime.BaseAPI {

    /**
     * Get a paginated list of posts from followed users or public posts
     * Get posts feed
     */
    async postsGetRaw(requestParameters: PostsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/posts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a paginated list of posts from followed users or public posts
     * Get posts feed
     */
    async postsGet(requestParameters: PostsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsGet200Response> {
        const response = await this.postsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get detailed information about a specific post
     * Get post details
     */
    async postsIdGetRaw(requestParameters: PostsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostsIdGet200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling postsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/posts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostsIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get detailed information about a specific post
     * Get post details
     */
    async postsIdGet(requestParameters: PostsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostsIdGet200Response> {
        const response = await this.postsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
