/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ShareGetRequest {
    threadId: string;
    scale?: number;
    lang?: string;
    sourceLang?: string;
}

/**
 * 
 */
export class ShareApi extends runtime.BaseAPI {

    /**
     * Download a long image representation of the thread for sharing, optionally in a translated language
     * Download share image
     */
    async shareGetRaw(requestParameters: ShareGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling shareGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['threadId'] != null) {
            queryParameters['thread_id'] = requestParameters['threadId'];
        }

        if (requestParameters['scale'] != null) {
            queryParameters['scale'] = requestParameters['scale'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        if (requestParameters['sourceLang'] != null) {
            queryParameters['source_lang'] = requestParameters['sourceLang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/share`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download a long image representation of the thread for sharing, optionally in a translated language
     * Download share image
     */
    async shareGet(requestParameters: ShareGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.shareGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
