/* tslint:disable */
/* eslint-disable */
/**
 * Threadmirror Backend API
 * API for managing user profiles and follows
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MeGet200Response,
} from '../models/index';
import {
    MeGet200ResponseFromJSON,
    MeGet200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class UserProfilesApi extends runtime.BaseAPI {

    /**
     * Retrieve the authenticated user\'s profile information including basic info, social stats, and content overview
     * Get current user profile
     */
    async meGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the authenticated user\'s profile information including basic info, social stats, and content overview
     * Get current user profile
     */
    async meGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeGet200Response> {
        const response = await this.meGetRaw(initOverrides);
        return await response.value();
    }

}
